### ISSUE TITLE
issue using datalist in bootstrap modal

### ISSUE THREAD

**Issue by koduri** [NonFactors/MVC5.Datalist.Web#1]
Hi there,

This is a great tool. i really like the way it is implemented.

I am having some issue using this control in bootstrap modal. Would you if it is possible to use this in modal?

**Comment by Muchiachio** [comment]
You would need to override [datalist partial (if necessary)](https://github.com/NonFactors/MVC5.Datalist/blob/develop/src/Datalist/Views/Shared/_Datalist.cshtml) and [datalist dialog initialization](https://github.com/NonFactors/MVC5.Datalist/blob/develop/src/Datalist/Scripts/Datalist/datalist.js) in various places, because there is hard coded code for opening, closing and centering the dialog using jQuery UI.
If it doesn't work or it's too much work to do, I would suggest restyling datalist dialog into bootstrap one.

**Comment by koduri** [comment]
Hi there,

Sorry for the delay and thank you for the prompt reply.

Just wondering if you are able to help in making this work with bootstrap modal.

Regards
Vasu

Get Outlook for Android<https://aka.ms/ghei36>



On Sun, Jul 24, 2016 at 12:31 AM +1000, "Muchiachio" <notifications@github.com<mailto:notifications@github.com>> wrote:


You would need to override datalist partial (if necessary)<https://github.com/NonFactors/MVC5.Datalist/blob/develop/src/Datalist/Views/Shared/_Datalist.cshtml> and datalist dialog initialization<https://github.com/NonFactors/MVC5.Datalist/blob/develop/src/Datalist/Scripts/Datalist/datalist.js> in various places, because there is hard coded code for opening, closing and centering the dialog using jQuery UI.
If it doesn't work or it's too much work to do, I would suggest restyling datalist dialog into bootstrap one.

-

**Comment by Muchiachio** [comment]
I can keep this issue open until you make bootstrap model work, given the changes needed above.
So I can answer any questions, if you will have them.

**Comment by Muchiachio** [comment]
Will you need any more help or I can close the issue (you can still leave a comment later if you want)?
